### ISSUE TITLE
unable to import workstation VM

### ISSUE THREAD

**Issue by Tefelbert** [Fortiphyd/GRFICSv2#14]
unable to import workstation vm, what to do?
![Capture](https://user-images.githubusercontent.com/73689893/207788194-0a0344bf-7416-47bc-a98d-f84cff1c4969.PNG)

**Comment by mmore21** [comment]
Ran into this problem as well earlier for the ScadaBR virtual machine which has a virtual disk image size of 100GB. Searching the error code brought up this [VirtualBox forum topic](https://forums.virtualbox.org/viewtopic.php?t=96290), which states that it is likely an error due to insufficient storage on the drive the virtual machine is being imported onto.
